const superheroes = [
    'Superman', 'Batman', 'Wonder Woman', 'Spider-Man', 'Iron Man',
    'Captain America', 'Black Widow', 'Thor', 'Hulk', 'Flash',
    'Green Lantern', 'Aquaman', 'Black Panther', 'Wolverine', 'Deadpool',
    'Supergirl', 'Green Arrow', 'Doctor Strange', 'Captain Marvel', 'Ant-Man',
    'Hawkeye', 'Black Canary', 'Daredevil', 'Cyborg', 'Scarlet Witch',
    'Professor X', 'Cyclops', 'Jean Grey', 'Storm', 'Wasp',
    'Luke Cage', 'Jessica Jones', 'Nightcrawler', 'Beast', 'Colossus',
    'Gambit', 'Rogue', 'Iceman', 'Shadowcat', 'Emma Frost',
    'Mr. Fantastic', 'Invisible Woman', 'Human Torch', 'Thing', 'Silver Surfer',
    'Black Bolt', 'Medusa', 'Crystal', 'Gorgon', 'Karnak',
    'Lockjaw', 'Moon Knight', 'Punisher', 'Ghost Rider', 'Blade',
    'Shang-Chi', 'Namor', 'Vision', 'Scarlet Spider', 'Miles Morales',
    'Jessica Drew', 'Ben Reilly', 'Silk', 'Carnage', 'Venom',
    'Mysterio', 'Green Goblin', 'Hobgoblin', 'Vulture', 'Rhino',
    'Sandman', 'Lizard', 'Electro', 'Kingpin', 'Bullseye',
    'Taskmaster', 'Ronin', 'Mockingbird', 'Squirrel Girl', 'Nova',
    'Adam Warlock', 'Quasar', 'Nova', 'War Machine', 'Winter Soldier',
    'Falcon', 'Agent 13', 'Star-Lord', 'Gamora', 'Drax',
    'Rocket Raccoon', 'Groot', 'Nick Fury', 'Maria Hill', 'Coulson',
    'Quake', 'Ghost', 'Elektra', 'Bucky Barnes', 'Shuri',
    'Okoye', 'Valkyrie', 'Korg', 'Nebula', 'Yondu',
    'Moonshadow', 'Spectra', 'Night Sentinel', 'Blaze Runner', 'Lunar Guardian',
    'Quantum Quasar', 'Starlight Scepter', 'Mystic Mirage', 'Eclipse Enigma', 'Solar Seraph',
    'Neon Nucleus', 'Galactic Glider', 'Thunder Tempest', 'Storm Striker', 'Astral Avenger',
    'Vortex Voyager', 'Celestial Cipher', 'Radiant Ray', 'Phoenix Fury', 'Aurora Archer',
    'Pulse Prism', 'Dimension Drifter', 'Chrono Crusader', 'Magnetic Maven', 'Luminary Lancer',
    'Vivid Vortex', 'Nebula Nomad', 'Cosmic Catalyst', 'Zephyr Zenith', 'Psyche Phantom',
    'Ethereal Elementor', 'Nebulous Nova', 'Velocity Vanguard', 'Pandora Paladin', 'Spectral Surge',
    'Aether Agent', 'Sonic Starshifter', 'Quantum Quiver', 'Luminous Labyrinth', 'Chronicle Captain',
    'Radiance Raptor', 'Nova Nomad', 'Quantum Quasar', 'Solaris Sorcerer', 'Ecliptic Element',
    'Supernova Squire', 'Zenith Zephyr', 'Aegis Aeon', 'Vortex Voyager', 'Lunar Luminary',
    'Zephyr Zenith', 'Flare Falcon', 'Lunar Lycan', 'Omega Oracle', 'Majestic Mirage',
    'Chrono Chameleon', 'Astral Alchemist', 'Vortex Vagabond', 'Solar Scepter', 'Stellar Sentinel',
    'Infinity Illuminator', 'Aeon Ascendant', 'Celestial Cipher', 'Quantum Quester', 'Eclipse Enchantress',
    'Radiant Ronin', 'Vivid Vigilante', 'Lunar Luminary', 'Zenith Zephyr', 'Quantum Quasar',
    'Ethereal Elementor', 'Sonic Starshifter', 'Luminous Labyrinth', 'Chronicle Captain', 'Radiance Raptor',
    'Aegis Aeon', 'Vortex Voyager', 'Lunar Luminary', 'Zephyr Zenith', 'Flare Falcon',
    'Lunar Lycan', 'Omega Oracle', 'Majestic Mirage', 'Chrono Chameleon', 'Astral Alchemist',
    'Vortex Vagabond', 'Solar Scepter', 'Stellar Sentinel', 'Infinity Illuminator', 'Aeon Ascendant',
    'Celestial Cipher', 'Quantum Quester', 'Eclipse Enchantress', 'Radiant Ronin', 'Vivid Vigilante',
  ];

const getrandomsuperhero = () => {
    return superheroes[Math.floor(Math.random() * superheroes.length)];
}
export default getrandomsuperhero;